name: flutter_phoenix
description: Easily restart your application from scratch, losing any previous state
version: 1.0.0
homepage: https://github.com/mobiten/flutter_phoenix
repository: https://github.com/mobiten/flutter_phoenix
issue_tracker: https://github.com/mobiten/flutter_phoenix/issues

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.4.1 <=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

